# docker-compose.yml
version: "3"
services:
  bunbi:
    image: bunbi/bunbi-node:v1.0.1
    network_mode: "host"
    restart: on-failure
    volumes:
      - chain_data:/data
    command: /usr/local/bin/bunbi-node
      --base-path /tmp/alice
      --chain local
      --alice
      --port 30333
      --ws-port 9945
      --rpc-port 9933
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
      --validator

volumes:
  chain_data:
    driver: local