# docker-compose.yml
version: "3"
services:
  bunbi:
    image: bunbi/dev:dev
    network_mode: "host"
    restart: on-failure
    volumes:
      - chain_data:/data
    command: /usr/local/bin/bunbi-node
      --wasm-execution Compiled
      --dev
      --db-cache 1024
      --rpc-cors "*"
      --port 30333
      --ws-port 9945
      --rpc-port 9933 
      --rpc-methods Unsafe 
      --ws-external

volumes:
  chain_data:
    driver: local