# docker-compose.yml
version: "3"
services:
  bunbi:
    image: bunbi/bunbi-node:v1
    network_mode: "host"
    restart: on-failure
    volumes:
      - chain_data:/data
    command: ./bunbi-node
      --wasm-execution Compiled
      --db-cache 1024
      --rpc-cors "*"
      --port 30333
      --ws-port 9333
      --validator
      --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWJYMksKfWMhBasGmmbgT41HFpCKNuebX9zMH9wR8RkbjV

volumes:
  chain_data:
    driver: local

